name: Quality Gates with SLOs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run lint
      run: npm run lint

    - name: Check linting errors
      run: |
        npm run lint
        if [ $? -ne 0 ]; then
          echo "Linting errors found"
          exit 1
        fi

    - name: Run tests
      run: npm test

    - name: Check test results
      run: |
        npm test
        if [ $? -ne 0 ]; then
          echo "Tests failed"
          exit 1
        fi

    - name: Run SLO checks
      run: |
        # Example command to fetch SLO data from a monitoring tool
        SLO_DATA=$(curl -s http://monitoring-tool/api/slo)
        ERROR_RATE=$(echo $SLO_DATA | jq '.error_rate')
        LATENCY=$(echo $SLO_DATA | jq '.latency')
        if [ $ERROR_RATE -gt 1 ]; then
          echo "Error rate above threshold"
          exit 1
        fi
        if [ $LATENCY -gt 200 ]; then
          echo "Latency above threshold"
          exit 1
        fi

    - name: Notify Slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: "Quality gate breached in workflow for Online Retail Demo project"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

